export const listaCategorias = [
  "Naturaleza",
  "Playa",
  "Comedia",
  "Viajes",
  "Comida",
  "Deportes",
  "Gym",
  "Danzas",
  "Arte y Creatividad",
  "Arquitectura",
  "Moda",
  "Animales",
  "Música",
  "Retratos",
  "Negocios y Finanzas",
  "Belleza y Estilo",
  "Cine",
  "Entretenimiento",
  "Fiestas y Eventos",
  "Cultura",
  "Tecnología",
  "Ciencia",
  "Bienestar",
  "Familia y Amigos",
  "Parejas",
  "Estilo de Vida",
  "Hobby y Pasatiempos",
  "Ciencia Ficción",
  "Fantasía",
  "Fotografía",
  "Paisajes",
  "Cómics",
  "Anime",
  "Reflexiones",
  "Educación",
  "Historia",
  "Literatura",
  "Curiosidades",
  "Mascotas",
];
